export const info = {
  projects: [
    {
      title: "The 100 Club",
      isFeatured: true,
      thumbnail: "/assets/portfolio-1.png",
      // githubUrl: "https://github.com/uzzii-21/astro-portfolio",
      liveUrl: "https://the100club.io/",
    },
    {
      title: "Donna",
      isFeatured: true,
      thumbnail: "/assets/portfolio-10.png",
      // githubUrl: "https://github.com/uzzii-21/astro-portfolio",
      liveUrl: "https://meetyourdonna.netlify.app/",
    },
    {
      title: "Olympus Origins",
      isFeatured: true,
      thumbnail: "/assets/portfolio-2.png",
      // githubUrl: "https://github.com/uzzii-21/astro-portfolio",
      liveUrl: "https://olympusorigins.com/",
    },
    {
      title: "Malcolm in the Middle",
      isFeatured: true,
      thumbnail: "/assets/portfolio-8.png",
      // githubUrl: "https://github.com/uzzii-21/astro-portfolio",
      liveUrl: "https://malcolminthemiddle.netlify.app/",
    },
    {
      title: "Punchin",
      isFeatured: true,
      thumbnail: "/assets/portfolio-3.png",
      // githubUrl: "https://github.com/uzzii-21/astro-portfolio",
      liveUrl: "https://punchinkeys.netlify.app/",
    },
    {
      title: "GMK ART",
      isFeatured: true,
      thumbnail: "/assets/portfolio-4.png",
      // githubUrl: "https://github.com/uzzii-21/astro-portfolio",
      liveUrl: "https://oo-gmkart.netlify.app/",
    },
    {
      title: "NodeFlair Clone",
      isFeatured: true,
      thumbnail: "/assets/portfolio-9.png",
      // githubUrl: "https://github.com/uzzii-21/astro-portfolio",
      liveUrl: "https://seantanyurong-nodeflair-assignment.vercel.app/",
    },
    {
      title: "Olympus Pages",
      isFeatured: true,
      thumbnail: "/assets/portfolio-5.png",
      // githubUrl: "https://github.com/uzzii-21/astro-portfolio",
      liveUrl: "https://olympuspages.netlify.app/",
    },
    {
      title: "One Olympus",
      isFeatured: true,
      thumbnail: "/assets/portfolio-6.png",
      // githubUrl: "https://github.com/uzzii-21/astro-portfolio",
      liveUrl: "https://oneolympus.com/",
    },
    {
      title: "Kolectiv",
      isFeatured: true,
      thumbnail: "/assets/portfolio-7.png",
      // githubUrl: "https://github.com/uzzii-21/astro-portfolio",
      liveUrl: "https://www.kolectivsg.com/",
    },
  ],
};
